### ISSUE TITLE
Network

### ISSUE THREAD

**Issue by MuhammadAhmed8** [charlieamer/python-remote-desktop-and-control#1]
Hi, could you tell the controller and controllee needs to be on the same LAN or they can be on different networks?

**Comment by charlieamer** [comment]
Easiest setup is through lan, it will work out of the box. If you want it over internet, you have to set up either port forwarding on server side or use a tunnel on server side (for example ngrok). Server can be either controller or controllee. I have used it successfully over internet with port forwarding, i was controller and server.On May 15, 2021 07:51, Muhammad Ahmed ***@***.***> wrote:
Hi, could you tell the controller and controllee needs to be on the same LAN or they can be on different networks?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

On May 15, 2021 07:51, Muhammad Ahmed ***@***.***> wrote:
Hi, could you tell the controller and controllee needs to be on the same LAN or they can be on different networks?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

On May 15, 2021 07:51, Muhammad Ahmed ***@***.***> wrote:
Hi, could you tell the controller and controllee needs to be on the same LAN or they can be on different networks?
